# Generated by Django 5.2.3 on 2025-06-18 18:57

from django.db import migrations

def seed_creative_fields(apps, schema_editor):
    CreativeField = apps.get_model('portfolio', 'CreativeField')
    presets = [
        # Art & Design
        "Graphic Design", "Illustration", "Fine Arts", "Painting", "Drawing",
        "Printmaking", "Sculpture", "Calligraphy", "Tattoo Art", "Fashion Design",
        "Textile Design", "Interior Design", "Architecture", "Product Design",
        "Industrial Design", "UX Design", "UI Design", "Jewelry Design",

        # Photography & Cinematography
        "Photography", "Photojournalism", "Cinematography", "Filmmaking",
        "Video Editing", "Directing", "Screenwriting", "Animation",
        "Motion Graphics", "Stop Motion", "Visual Effects (VFX)", "Drone Photography",

        # Performance & Entertainment
        "Acting", "Dance", "Theatre", "Musical Theatre", "Stage Design",
        "Voice Acting", "Comedy", "Choreography",

        # Music & Audio
        "Music", "Music Production", "Sound Design", "Singing", "DJing",
        "Instrumentalist", "Songwriting", "Composing", "Audio Engineering",
        "Podcasting", "Sound Mixing", "Foley Art",

        # Digital & Interactive Media
        "Web Design", "Web Development", "Game Design", "Game Development",
        "App Development", "Augmented Reality (AR)", "Virtual Reality (VR)",
        "3D Modeling", "Creative Coding", "Generative Art",
        "Interactive Installations", "Multimedia Art",

        # Writing & Communication
        "Creative Writing", "Journalism", "Content Writing", "Copywriting",
        "Technical Writing", "Poetry", "Blogging", "Storyboarding",
        "Editing", "Grant Writing",

        # Marketing, Strategy & Business
        "Marketing", "Branding", "Social Media Strategy", "Advertising",
        "Influencer Marketing", "Entrepreneurship", "Creative Direction",
        "Business Strategy", "Growth Marketing", "E-commerce",

        # Data, Research & Analysis
        "Data Analysis", "Data Visualization", "Market Research",
        "User Research", "UX Research", "Business Intelligence", "Data Journalism"
    ]
    for name in presets:
        CreativeField.objects.get_or_create(name=name)

class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
    ]
