# Generated by Django 5.2.3 on 2025-06-18 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_seed_creative_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfoliolink',
            name='name',
            field=models.CharField(max_length=25),
        ),
    ]
